import Head from "next/head";
import { client } from "../lib/contentful/client";
import styles from "@/styles/Home.module.css";
import LandingSection from "./LandingSection";
import VideoSection from "./VideoSection";
import BannerSection from "./BannerSection";
import PartnersSection from "./PartnersSection";
import ProjectionSection from "./ProjectionSection";
import { createClient } from "contentful";
import ChatBotSection from "./ChatBotSection";
import FeatureBanner from "@/components/FeatureBanner";
import Categories from "./Categories";
import IndustryExpertise from "./IndustryExpertise";
import CaseStudy from "./CaseStudy";
import OurProducts from "./OurProducts";
import Investors from "./Investments";

interface Entry {
  fields: {
    mainVideo: {
      fields: {
        file: {
          url: string;
        };
      };
    };
  };
}
interface APIResponse {
  items: Entry[];
}

export async function getStaticProps() {
  // Assuming your API response has the type APIResponse
  const res: APIResponse = await client.getEntries({
    content_type: "homepage",
  });

  // Use optional chaining to access the properties safely
  const mainVideoUrl = res?.items[0]?.fields.mainVideo?.fields.file?.url;

  return {
    props: {
      homepageVideo: mainVideoUrl,
    },
  };
}

type Props = {
  homepageVideo: string;
};

export default function Home({ homepageVideo }: Props) {
  return (
    <>
      <Head>
        <title>JNET</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/gyt_logo_icon_PZt_icon.ico" />
      </Head>

      <LandingSection mainVideoURL={homepageVideo} />
      <VideoSection />
      <BannerSection />
      <ProjectionSection />
      {/* <IndustryExpertise />
      <CaseStudy /> */}
      <OurProducts />
      <PartnersSection partners={[]} />
      <Investors />
      <ChatBotSection />
    </>
  );
}
