export const services = [
  {
    id: "CADS",
    category: "Our Services",
    heading: "Software Development",
    text: "Being a full-stack, multidisciplinary custom software development company with over a decade of experience, JNET has been instrumental in creating impactful custom-built software for leading companies across industries. We provide end-to-end custom software development services and turn technology solutions into growth enablers with our profound expertise, technological vision, and streamlined processes. Our technologically savvy developers will support you from early ideation and solution discovery through quality control and continuous delivery of new features. ",
    image: "/assets/images/ServiceBigPic.png",
    services: [
      {
        id: "OPD",
        category: "SoftwareDevelopment",
        heading: "Out Sourced Product Development",
        text: "Leverage Agile Methodology and Navigate the Digital Landscape",
      },
      {
        id: "APD",
        category: "SoftwareDevelopment",
        heading: "Application Development",
        text: "",
      },
      {
        id: "AMS",
        category: "SoftwareDevelopment",
        heading: "Application Maintenance and Support",
        text: "",
      },
    ],
  },
  {
    id: "AMLS",
    category: "Our Services",
    heading: "Mobile Application Development",
    text: "JNET offers full-stack mobile app development to help companies strategize, develop, and scale dynamic mobile app solutions in enhancing their business performance and enabling innovative growth opportunities. Whether it is end-to-end development or project management, JNET specializes in both native and cross-platform development. Our expertise in mobile apps development will help you create practical and seamless experiences on any device and get the best of mobile technology for your business.",
    image: "/assets/images/ServiceMobileBigPic.png",
    services: [
      {
        id: "FCMADS",
        category: "MobileApplicationDevelopment",
        heading: "Full-cycle Mobile Application Development Services",
        text: "",
      },
      {
        id: "BMMADS",
        category: "MobileApplicationDevelopment",
        heading: "Mobile Applications in Sync with Your Business Model",
        text: "",
      },
      {
        id: "TCTP",
        category: "MobileApplicationDevelopment",
        heading: "Technology Competencies and Technology Platforms",
        text: "",
      },
    ],
  },
  {
    id: "DACS",
    category: "Our Services",
    heading: "IT Infrastructure",
    text: "Organizations today are plagued with a variety of IT Infrastructure requirements as technology has impacted and improved the way they conduct their business, including communication, productivity, and speed in making business decisions. JNET with its unique approach to IT Infrastructure Management provides reliable, effective, and remote IT infrastructure support and offers Strategic Planning, Implementation, Management, Maintenance and Security solutions for Windows, Linux and Cloud infrastructure.",
    image: "/assets/images/infrastructure.png",
    services: [
      {
        id: "RIS",
        category: "ITInfrastructure",
        heading:
          "Scalable, Flexible, Reliable, And Remote It Infrastructure Services",
        text: "",
      },
      {
        id: "IBP",
        category: "ITInfrastructure",
        heading: "Industry Best-Practices",
        text: "",
      },
    ],
  },
  {
    id: "PM",
    category: "Our Services",
    heading: "Staffing Services",
    text: "Innovation and technology are driving the world forward with advances occurring in many sectors including cloud security, AI, IoT, automation, and business systems. To help organizations run their business and better serve their customers, having a talent pool of technical leaders, developers, and engineers is vital. This is where JNET Technologies steps in. With our proven sourcing strategy and recruiting approach, we can find the right people, with the right skills, for the right job. Whether you’re looking to extend your capabilities or fill workforce gaps, we bridge the IT talent demand-supply gap by placing highly qualified professionals to deliver results for you so you can meet challenges and seize opportunities.",
    image: "/assets/images/Staffing.png",
    services: [
      {
        id: "SB",
        category: "StaffingServices",
        heading: "Staffing Business",
        text: "",
      },
      {
        id: "SE",
        category: "StaffingServices",
        heading: "Staffing Excellence",
        text: "",
      },
      {
        id: "DIF",
        category: "StaffingServices",
        heading: "Differentiators",
        text: "",
      },
      {
        id: "OSP",
        category: "StaffingServices",
        heading: "Our Selection Process",
        text: "",
      },
      {
        id: "EM",
        category: "Staffing Services",
        heading: "Engagement Models",
        text: "",
      },
      {
        id: "FHO",
        category: "Staffing Services",
        heading: "Flexible Hiring Options",
        text: "",
      },
    ],
  },
  {
    id: "SD",
    category: "Our Services",
    heading: "Telecom Services",
    text: "Telecom Service Providers must enhance their agility in responding to the evolving global telecommunication practices. It is achieved only by rationalizing their data infrastructures, therefore gaining the potential to significantly reduce their data management costs and offer superior customer service. With an ability to support Telecom assets that include circuits, stations, contracts, locations, and wireless devices, JNET Technologies is one of the emerging companies that can provide end-to-end Telecom infrastructure service provisioning. Over the years, we have developed competencies in designing and building various infrastructures, site acquisitions, and 24X7 Operation and Maintenance support.",
    image: "/assets/images/Telecom.png",
    services: [
      {
        id: "OSI",
        category: "TelecomServices",
        heading: "Our Services Include",
        text: "",
      },
      {
        id: "IBP",
        category: "TelecomServices",
        heading: "Industry Best-Practices",
        text: "",
      },
      {
        id: "TIS",
        category: "TelecomServices",
        heading: "Why Leverage Our Telecom Infrastructure Services?",
        text: "",
      },
    ],
  },
  {
    id: "AB",
    category: "Our Services",
    heading: "Data Warehousing (DW) and Business Intelligence (BI)",
    text: "Making data-driven decisions only after considering all relevant business data from various sources and formats in silos with their unexplored relations can help any organization succeed. JNET, with its deep domain expertise and rich experience in Data Warehousing (DW) and Business Intelligence (BI), has successfully designed, developed, and implemented data warehousing and Business Intelligence (BI) solutions for a number of its clients.",
    image: "/assets/images/DW&BI.png",
    services: [
      {
        id: "OYD",
        category: "DW&BI",
        heading: "Organizing Your Data into a Single Source of Truth",
        text: "",
      },
      {
        id: "LLTD",
        category: "DW&BI",
        heading: "Leveraging Leading Technologies to Deliver Excellence",
        text: "",
      },
    ],
  },
  {
    id: "UUCS",
    category: "Our Services",
    heading: "UX & UI Design and Consulting Services",
    text: "JNET Design Studio is a team of 150+ design consultants, UI/UX designers, researchers, and design engineers. Over 3+ years, we gathered a great deal of experience in different types of digital solutions in Finance, Healthcare and Life Sciences, Travel and Hospitality, Media and Entertainment, Retail and Distribution, among other industries. ",
    image: "/assets/images/UI&UX.png",
    services: [
      {
        id: "OYD",
        category: "UIUX",
        heading: "UI/UX Design Services for a Unique Digital Experience",
        text: "",
      },
      {
        id: "TS",
        category: "UIUX",
        heading: "Technical Services",
        text: "",
      },
      {
        id: "TT",
        category: "UIUX",
        heading: "UI/UX Tools and Technologies We Use",
        text: "",
      },
    ],
  },
  {
    id: "LM",
    category: "Our Services",
    heading: "QA/Testing",
    text: "JNET ensures software quality and usability with quality assurance & testing services that perfectly fit the client’s business objectives. We will modernize your platform for a faster, easier, safer customer and user experience through our innovative, scalable, and advanced QA and testing services. Our services are delivered through JNET Standard Testing Solutions, which received the highest industry quality accreditations With the strongest QA and testing expertise, we skillfully use our engineering-led process discipline to accelerate releases, lower expenses, enhance accuracy and redeploy resources to matters that need their prioritized attention. With the strongest QA and testing expertise, we skillfully use our engineering-led process discipline to accelerate releases, lower expenses, enhance accuracy and redeploy resources to matters that need their prioritized attention.",
    image: "/assets/images/QA.png",
    services: [
      {
        id: "WAT",
        category: "QATesting",
        heading: "Web Application Testing",
        text: "",
      },
      {
        id: "DAT",
        category: "QATesting",
        heading: "Desktop Application Testing",
        text: "",
      },
      {
        id: "PT",
        category: "QATesting",
        heading: "Performance Testing",
        text: "",
      },
      {
        id: "ST",
        category: "QATesting",
        heading: "Security Testing",
        text: "",
      },
      {
        id: "CPT",
        category: "QATesting",
        heading: "Cross-platform Testing",
        text: "",
      },
      {
        id: "MT",
        category: "QATesting",
        heading: "Mobile Testing",
        text: "",
      },
      {
        id: "AT",
        category: "QATesting",
        heading: "Automation Testing",
        text: "",
      },
    ],
  },
  {
    id: "MS",
    category: "Operate",
    heading: "Managed Support",
    text: "JNET provides support and maintenance services for systems in production. Clients that subscribe to our support services gain access to experts with first-hand knowledge of their systems and benefit from increased reliability of business-critical applications and guaranteed prompt reaction time. By using JNET’s managed support services, our clients significantly reduce the cost of application ownership and keep their system functionality up-to-date while focusing on their core business tasks. We offer a variety of subscription-based support options ",
    image: "/assets/images/QA.png",
  },
  {
    id: "SRE",
    category: "Operate",
    heading: "SRE",
    text: "Bridge the gap between software development and operations with the Site Reliability Engineering approach (SRE). Ensure better collaboration between engineers and product owners, reduce costs and focus on efforts that will bring long-term value to the system. Partner with DataArt, an experienced SRE service provider, to create scalable and highly reliable software systems.",
    image: "/assets/images/QA.png",
  },
  {
    id: "STS",
    category: "Operate",
    heading: "Security Testing Service",
    text: "Security testing services can help prevent virus outbreaks, IT staff negligence, and regulatory non-compliance. Any product development life cycle should include a security testing stage to prevent a company from data breaches, ensure compliance and avoid security vulnerabilities. It can be challenging to navigate the complex security landscape alone. JNET is a trusted security testing company that can help your organization prepare, detect, react, and recover from security breaches along software development life cycle. Our company has the necessary cyber security testing resources to protect your sensitive business data from attacks.",
    image: "/assets/images/QA.png",
  },
  {
    id: "ASD",
    category: "Build",
    heading: "Agile Software Development",
    text: "JNET’s Agile approach allows us to develop high-quality software that meets stakeholders’ changing needs cost-effectively and faster than ever before. We also help clients build Agile capabilities and implement Agile concepts and methodologies.",
    image: "/assets/images/QA.png",
  },
  {
    id: "DPE",
    category: "Build",
    heading: "DevOps and Platform Engineering",
    text: "Looking to save time and money with DevOps practices and services like agility, automation, continuity, and governance? Turn to DataArt to implement DevOps best practices, including integration with cloud, continuous integration and continuous delivery (CI/CD), GitOps, containerization, DevSecOps, AI/ML, and AI Ops, as well as a host of other services. Automate and coordinate software development life cycle (SDLC) processes like development, security, testing, deployment with DataArt, a DevOps solutions provider.",
    image: "/assets/images/QA.png",
  },
  {
    id: "QPE",
    category: "Build",
    heading: "Quality and Performance Engineering",
    text: "Quality Assurance (QA) activities are crucial for the success of any project and should start simultaneously or even before development, when the first project requirements are specified. Each QA phase includes time for test plan development and for intensive ongoing testing. At the end of each phase, time for stabilization, regression, and post-deployment testing must be reserved. Another important role of quality assurance engineers is to be internal product owners: have the necessary understanding of the system, which ensures a fully functional testing on the one hand, and development team expertise – on the other.",
    image: "/assets/images/QA.png",
  },
];
